server:
  port: 4399

spring:
  application:
    name: api-gateway
#  main:
#    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9527/eureka
#  instance:
#    prefer-ip-address: true

#路由
zuul:
  routes:
    login:
      path: /login/**
      serviceId: login
    register:
      path: /register/**
      serviceId: register
  ignored-services: "*"

#设置超时时间
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

