server:
  port: 4399

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9527/eureka
  #使用ip地址
  instance:
    prefer-ip-address: true

zuul:
  routes:
    login:
      path: /login/**
      serviceId: login
    register:
      path: /register/**
      serviceId: register
    topic:
      path: /topic/**
      serviceId: topic
    sms:
      path: /sms/**
      serviceId: sms
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

#设置超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  eureka:
    enable: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000





