server:
  port: 2222
project:
  host: 127.0.0.1

spring:
  application:
    name: login
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.145.221:3306/lover?characterEncoding=utf-8
    username: root
    password: 0
  main:
    allow-bean-definition-overriding: true     #覆盖相同名称的bean
#  jpa:
#    database: MySQL
#    generate-ddl: false
#    show-sql: true
#    properties:
#      hibernate:
#          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 120.77.145.221
    post: 6379
    database: 2
    password:
    timeout: 1800000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9527/eureka
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml



#pageHelper插件配置
pagehelper:
  helper-dialect: mysql   #数据库连接
  reasonable: true        #分页合理化参数
